### ISSUE TITLE
avnav-ocharts-plugin : Depends: libwxgtk3.0-0v5 but it is not installable. On RaspiOS Bullseye

### ISSUE THREAD

**Issue by mgrouch** [wellenvogel/avnav-ocharts-provider#19]
The following packages have unmet dependencies:
 avnav-ocharts-plugin : Depends: libwxgtk3.0-0v5 but it is not installable
                        Depends: avnav-ocharts but it is not installable or
                                 avnav-oesenc but it is not going to be installed
                        Recommends: avnav-ocharts but it is not installable

Thanks,

**Comment by wellenvogel** [comment]
should be resolved with the newest release 20220225.
