### ISSUE TITLE
Osharts Provider listens only under localhost

### ISSUE THREAD

**Issue by qMalte** [wellenvogel/avnav-ocharts-provider#22]
Hello all,

I have the osharts server only listening on the hostname: localhost or 127.0.0.1. Therefore I can't call it via a client under the private IP of the Raspberry PI.
Is the error known by chance? The installation of avnav was done via OpenPlotter.

I am looking forward to your suggestions and ideas.

Many greetings

Malte

**Comment by wellenvogel** [comment]
Could you provide some more details?
So how you tested this and how you checked the listening address?

**Comment by qMalte** [comment]
When I call avnav directly on the Raspberry PI (http://localhost:8080), everything works fine. However, when I call avnav on a client (tablet) under the IP: 192.168.123.200:8080, avnav works but without the osharts plugin.

**Comment by wellenvogel** [comment]
Hmm- looks strange.
Not sure if there is any firewall in between...
The only thing that will not work at all:
Access to o-charts from a routed network. This is a legal issue (license restrictions of the charts).
So you must ensure to access them from a net that is directly connected to the pi.
Can you check this (you can use `ip addr show` on the pi).
So as long as you are connected to the access point provided by the pi or from a network that is only using a switch - it should work.
Additionally there is a limit of 5 simultaneous clients.
See also https://www.wellenvogel.net/software/avnav/docs/hints/ocharts.html?lang=en#h2:LicenseNotes

**Comment by wellenvogel** [comment]
As there is no response, I close this issue. Feel free to reopen...
