### ISSUE TITLE
New O-charts system

### ISSUE THREAD

**Issue by Fietsenwiel** [wellenvogel/avnav-ocharts-provider#27]
Hi, I can't find it anywhere but is "Avnac o-charts" also addapted to the new o-charts system.
I understood the have changed their system from today with the possibility to updat parts of a chart.

**Comment by wellenvogel** [comment]
https://www.wellenvogel.net/software/avnav/docs/hints/ocharts.html?lang=en#h2:Releases
So -yes, adapted.
But incremental updates are not supported. The flow remains as it is.
You can at any point in time request a new version and install it (as until now).
Not sure if I will ever implement the interface to the shop directly (online process) - as this would be necessary for incremental updates...
